### ISSUE TITLE
Change `toString` method of `Vulnerabilities`

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#290]
The information provided by the `toString` method of `Vulnerabilities` is a bit misleading in combination with the `InfoAboutVulnerabilities` and `OssFeature.VULNERABILITIES` with the name `Info about vulnerabilities in open-source project`.

As it may lead to something like "Info about vulnerabilities in open-source project: 47 vulnerabilities" if someone do a 
```
String sample = feature.name() + ": " + feature.value();
```

Recommend something like below which produce for above sample e.g.: "Info about vulnerabilities in open-source project: 1 UNKNOWN vulnerability; 2 UNPATCHED vulnerabilities; 2 PATCHED vulnerabilities".

Can also provide an according PR if wished.

```
  @Override
  public String toString() {
    if (entries.isEmpty()) {
      return "No vulnerabilities found";
    }
    return entries.stream().collect(Collectors.groupingBy(Vulnerability::resolution))
      .entrySet().stream()
      .map((entry) -> {
        int size = entry.getValue().size();
        return String.format("%d %s %s", size, entry.getKey(), size == 1 ? "vulnerability" : "vulnerabilities");
      }).collect(Collectors.joining("; "));
  }
```

**Comment by artem-smotrakov** [comment]
The `Vulnerability` class contains multiple fields that hold info about a vulnerability including resolution status. The current `Vulnerabilities.toString()` method is very simple and prints out just a number of vulnerabilities in a collection. One may want the method to print statistics about resolution, another one may want it to print vulnerability ids and so on. It depends. In fact, the method exists just to avoid calling the `Object.toString()` method that prints out something like `z.y.x.Vulnerabilities@abcdef`.

I would prefer to keep the method simple, and I would let applications implement their own methods that prints info about vulnerabilities the way they need it. If you still think the method needs to be updated, then go ahead and open a pull request. Then, I would suggest use lower case, `,` instead of `;`, and mention somehow that `UNKNOWN` is a resolution status.

**Comment by mibo** [comment]
> One may want the method to print statistics about resolution, another one may want it to print vulnerability ids and so on.

Yes, you are right. In my use case we need just some information if the vulnerabilities are open or patched. Other may not interested in this.
Guess best would be that the `toString()` will remain as simple as possible and in our service we change the way how we convert a feature value into a `String`.
